# Generated by Django 5.0.6 on 2024-06-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('ID_Cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=64)),
                ('Descripcion', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False)),
                ('curso_certificado', models.CharField(max_length=255)),
                ('nivel_certificado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('ID_Departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_Departamento', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('competencias_evaluadas', models.CharField(max_length=255)),
                ('result_evaluacion', models.CharField(max_length=255)),
                ('duracion_evaluacion', models.IntegerField()),
                ('estado_evaluacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id_experiencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lugar', models.CharField(max_length=255)),
                ('cargo_ejercido', models.CharField(max_length=255)),
                ('tiempo_ejercido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('conocimiento_req', models.CharField(max_length=255)),
                ('anos_exp', models.IntegerField()),
                ('titulo_requerido', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id_curriculum', models.AutoField(primary_key=True, serialize=False)),
                ('grado_educacion', models.CharField(max_length=255)),
                ('id_certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.certificados')),
                ('id_experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.experiencialaboral')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id_cand', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cand', models.CharField(max_length=255)),
                ('apell_cand', models.CharField(max_length=255)),
                ('fecha_nac_cand', models.DateField()),
                ('direccion_cand', models.CharField(max_length=255)),
                ('correo_cand', models.EmailField(max_length=254)),
                ('num_telefono', models.CharField(max_length=15)),
                ('id_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('ID_Empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_Empleado', models.CharField(max_length=32)),
                ('Apellido_Empleado', models.CharField(max_length=32)),
                ('Telefono', models.CharField(max_length=15)),
                ('Direccion', models.CharField(max_length=64)),
                ('Correo', models.CharField(max_length=64, unique=True)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Cant_Hijos', models.IntegerField(default=0)),
                ('Estado_Civil', models.CharField(max_length=15)),
                ('DNI', models.CharField(max_length=8)),
                ('Fecha_Ingreso', models.DateField()),
                ('ID_Cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cargo')),
                ('ID_Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudEmpleo',
            fields=[
                ('id_solicitud', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('id_vacante', models.CharField(max_length=8)),
                ('est_solicitud', models.CharField(max_length=255)),
                ('horario_disponible', models.CharField(max_length=255)),
                ('fecha_aplicacion', models.DateField()),
                ('id_cand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id_entrevista', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_eva', models.DateField()),
                ('hora_entrevista', models.TimeField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.empleado')),
                ('id_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.evaluacion')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.solicitudempleo')),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id_vac', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=255)),
                ('beneficio', models.CharField(max_length=255)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('horario', models.CharField(max_length=255)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cargo')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.departamento')),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.perfil')),
            ],
        ),
    ]
