# Generated by Django 5.0.6 on 2024-06-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0003_alter_programa_capacitador_id_departamento_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departamento',
            table='departamento',
        ),
    ]
